//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caredev.MegoTools.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caredev.MegoTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消(_C) 的本地化字符串。
        /// </summary>
        public static string AdvancedProperty_Cancel {
            get {
                return ResourceManager.GetString("AdvancedProperty_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定(_O) 的本地化字符串。
        /// </summary>
        public static string AdvancedProperty_Ok {
            get {
                return ResourceManager.GetString("AdvancedProperty_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级属性 的本地化字符串。
        /// </summary>
        public static string AdvancedProperty_Title {
            get {
                return ResourceManager.GetString("AdvancedProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定在映射类型中的属性注释。 的本地化字符串。
        /// </summary>
        public static string ColumnElement_Comments_Description {
            get {
                return ResourceManager.GetString("ColumnElement_Comments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释 的本地化字符串。
        /// </summary>
        public static string ColumnElement_Comments_Name {
            get {
                return ResourceManager.GetString("ColumnElement_Comments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在提交时参与乐观并发检查。 的本地化字符串。
        /// </summary>
        public static string ColumnElement_ConcurrencyCheck_Description {
            get {
                return ResourceManager.GetString("ColumnElement_ConcurrencyCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并发检查 的本地化字符串。
        /// </summary>
        public static string ColumnElement_ConcurrencyCheck_Name {
            get {
                return ResourceManager.GetString("ColumnElement_ConcurrencyCheck_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列是否可以为空。 的本地化字符串。
        /// </summary>
        public static string ColumnElement_IsNullable_Description {
            get {
                return ResourceManager.GetString("ColumnElement_IsNullable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为空 的本地化字符串。
        /// </summary>
        public static string ColumnElement_IsNullable_Name {
            get {
                return ResourceManager.GetString("ColumnElement_IsNullable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定在映射类型中的属性名。 的本地化字符串。
        /// </summary>
        public static string ColumnElement_PropertyName_Description {
            get {
                return ResourceManager.GetString("ColumnElement_PropertyName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名 的本地化字符串。
        /// </summary>
        public static string ColumnElement_PropertyName_Name {
            get {
                return ResourceManager.GetString("ColumnElement_PropertyName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定数据库中存储的类型。 的本地化字符串。
        /// </summary>
        public static string ColumnElement_TypeName_Description {
            get {
                return ResourceManager.GetString("ColumnElement_TypeName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型名 的本地化字符串。
        /// </summary>
        public static string ColumnElement_TypeName_Name {
            get {
                return ResourceManager.GetString("ColumnElement_TypeName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在数据库中是否固定长度 的本地化字符串。
        /// </summary>
        public static string ColumnLengthElement_IsFixed_Description {
            get {
                return ResourceManager.GetString("ColumnLengthElement_IsFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定长度 的本地化字符串。
        /// </summary>
        public static string ColumnLengthElement_IsFixed_Name {
            get {
                return ResourceManager.GetString("ColumnLengthElement_IsFixed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在数据库中的最大长度 的本地化字符串。
        /// </summary>
        public static string ColumnLengthElement_MaxLength_Description {
            get {
                return ResourceManager.GetString("ColumnLengthElement_MaxLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大长度 的本地化字符串。
        /// </summary>
        public static string ColumnLengthElement_MaxLength_Name {
            get {
                return ResourceManager.GetString("ColumnLengthElement_MaxLength_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在数据库中的数据精度。 的本地化字符串。
        /// </summary>
        public static string ColumnPrecisionElement_Precision_Description {
            get {
                return ResourceManager.GetString("ColumnPrecisionElement_Precision_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精度 的本地化字符串。
        /// </summary>
        public static string ColumnPrecisionElement_Precision_Name {
            get {
                return ResourceManager.GetString("ColumnPrecisionElement_Precision_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在数据库中的小数位数。 的本地化字符串。
        /// </summary>
        public static string ColumnPrecisionElement_Scale_Description {
            get {
                return ResourceManager.GetString("ColumnPrecisionElement_Scale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数位数 的本地化字符串。
        /// </summary>
        public static string ColumnPrecisionElement_Scale_Name {
            get {
                return ResourceManager.GetString("ColumnPrecisionElement_Scale_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定当前列在数据库中是否使用Unicode编码。 的本地化字符串。
        /// </summary>
        public static string ColumnStringElement_IsUnicode_Description {
            get {
                return ResourceManager.GetString("ColumnStringElement_IsUnicode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode 的本地化字符串。
        /// </summary>
        public static string ColumnStringElement_IsUnicode_Name {
            get {
                return ResourceManager.GetString("ColumnStringElement_IsUnicode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载连接信息发生错误：{0} 的本地化字符串。
        /// </summary>
        public static string ConnectionInfo_ReloadError {
            get {
                return ResourceManager.GetString("ConnectionInfo_ReloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存连接信息发生错误：{0} 的本地化字符串。
        /// </summary>
        public static string ConnectionInfo_SaveError {
            get {
                return ResourceManager.GetString("ConnectionInfo_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级(_V)… 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Advanced {
            get {
                return ResourceManager.GetString("CreateConnection_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消(_C) 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Cancel {
            get {
                return ResourceManager.GetString("CreateConnection_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接名称: 的本地化字符串。
        /// </summary>
        public static string CreateConnection_ConnectionName {
            get {
                return ResourceManager.GetString("CreateConnection_ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新连接 的本地化字符串。
        /// </summary>
        public static string CreateConnection_DefaultName {
            get {
                return ResourceManager.GetString("CreateConnection_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入信息以连接到选定提供程序的数据源，或从下拉框中选择另一个提供程序。 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Head {
            get {
                return ResourceManager.GetString("CreateConnection_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接名称不能为空。 的本地化字符串。
        /// </summary>
        public static string CreateConnection_NameCannotNull {
            get {
                return ResourceManager.GetString("CreateConnection_NameCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定(_O) 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Ok {
            get {
                return ResourceManager.GetString("CreateConnection_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供程序: 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Provider {
            get {
                return ResourceManager.GetString("CreateConnection_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接成功。 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Sucess {
            get {
                return ResourceManager.GetString("CreateConnection_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试连接(_T) 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Test {
            get {
                return ResourceManager.GetString("CreateConnection_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加连接 的本地化字符串。
        /// </summary>
        public static string CreateConnection_Title {
            get {
                return ResourceManager.GetString("CreateConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览(_B)... 的本地化字符串。
        /// </summary>
        public static string FileConnection_Browse {
            get {
                return ResourceManager.GetString("FileConnection_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建(_C)... 的本地化字符串。
        /// </summary>
        public static string FileConnection_Create {
            get {
                return ResourceManager.GetString("FileConnection_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库文件名(_D): 的本地化字符串。
        /// </summary>
        public static string FileConnection_FileName {
            get {
                return ResourceManager.GetString("FileConnection_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录到数据库 的本地化字符串。
        /// </summary>
        public static string FileConnection_GroupHost {
            get {
                return ResourceManager.GetString("FileConnection_GroupHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码(_P): 的本地化字符串。
        /// </summary>
        public static string FileConnection_Password {
            get {
                return ResourceManager.GetString("FileConnection_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt; 上一步(_P) 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Back {
            get {
                return ResourceManager.GetString("NewItemWizard_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消(_C) 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Cancel {
            get {
                return ResourceManager.GetString("NewItemWizard_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在写入配置 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Configure {
            get {
                return ResourceManager.GetString("NewItemWizard_Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成(_F) 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Finish {
            get {
                return ResourceManager.GetString("NewItemWizard_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择您希望使用的数据库对象并对生成代码进行相关设置。 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_FinishPage_Descript {
            get {
                return ResourceManager.GetString("NewItemWizard_FinishPage_Descript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您要在模型中包括哪些数据库对象？ 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_FinishPage_Header {
            get {
                return ResourceManager.GetString("NewItemWizard_FinishPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定所生成对象名称的单复数形式(_S) 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_FinishPage_Pluralization {
            get {
                return ResourceManager.GetString("NewItemWizard_FinishPage_Pluralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在模型中生成关系 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_FinishPage_Relation {
            get {
                return ResourceManager.GetString("NewItemWizard_FinishPage_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择数据库对象 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_FinishPage_Title {
            get {
                return ResourceManager.GetString("NewItemWizard_FinishPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在生成内容 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Generate {
            get {
                return ResourceManager.GetString("NewItemWizard_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步(_N) &gt; 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Next {
            get {
                return ResourceManager.GetString("NewItemWizard_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备Nuget包 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Nuget {
            get {
                return ResourceManager.GetString("NewItemWizard_Nuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的应用程序应使用哪个数据连接与数据误国进行连接？ 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_App {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前连接设置另存为(_S): 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_Config {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接字符串: 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_ConnectionString {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库: 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_Database {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择您希望使用的数据连接，用于 Mego 连接到指定数据库。 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_Descript {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_Descript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建连接(_D) 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_NewConnection {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择数据连接 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_SettingPage_Title {
            get {
                return ResourceManager.GetString("NewItemWizard_SettingPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建Mego数据模型向导 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_Title {
            get {
                return ResourceManager.GetString("NewItemWizard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在准备 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_WaitText {
            get {
                return ResourceManager.GetString("NewItemWizard_WaitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_WaitTitle {
            get {
                return ResourceManager.GetString("NewItemWizard_WaitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本向导将引导您一步步创建基于 Mego。 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_WelcomePage_Descript {
            get {
                return ResourceManager.GetString("NewItemWizard_WelcomePage_Descript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 Mego 的本地化字符串。
        /// </summary>
        public static string NewItemWizard_WelcomePage_Title {
            get {
                return ResourceManager.GetString("NewItemWizard_WelcomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于指定生成定义类的类名。 的本地化字符串。
        /// </summary>
        public static string ObjectElement_ClassName_Description {
            get {
                return ResourceManager.GetString("ObjectElement_ClassName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型名 的本地化字符串。
        /// </summary>
        public static string ObjectElement_ClassName_Name {
            get {
                return ResourceManager.GetString("ObjectElement_ClassName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定在映射类型的注释。 的本地化字符串。
        /// </summary>
        public static string ObjectElement_Comments_Description {
            get {
                return ResourceManager.GetString("ObjectElement_Comments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释 的本地化字符串。
        /// </summary>
        public static string ObjectElement_Comments_Name {
            get {
                return ResourceManager.GetString("ObjectElement_Comments_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于指定生成在数据上下文中的属性名称。 的本地化字符串。
        /// </summary>
        public static string ObjectElement_PropertyName_Description {
            get {
                return ResourceManager.GetString("ObjectElement_PropertyName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名 的本地化字符串。
        /// </summary>
        public static string ObjectElement_PropertyName_Name {
            get {
                return ResourceManager.GetString("ObjectElement_PropertyName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string PropertyGrid_Category_Common {
            get {
                return ResourceManager.GetString("PropertyGrid_Category_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string PropertyGrid_Category_Length {
            get {
                return ResourceManager.GetString("PropertyGrid_Category_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精度 的本地化字符串。
        /// </summary>
        public static string PropertyGrid_Category_Precision {
            get {
                return ResourceManager.GetString("PropertyGrid_Category_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串 的本地化字符串。
        /// </summary>
        public static string PropertyGrid_Category_String {
            get {
                return ResourceManager.GetString("PropertyGrid_Category_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数据库名称(_D): 的本地化字符串。
        /// </summary>
        public static string ServerConnection_Database {
            get {
                return ResourceManager.GetString("ServerConnection_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接到数据库 的本地化字符串。
        /// </summary>
        public static string ServerConnection_GroupDb {
            get {
                return ResourceManager.GetString("ServerConnection_GroupDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录到服务器 的本地化字符串。
        /// </summary>
        public static string ServerConnection_GroupHost {
            get {
                return ResourceManager.GetString("ServerConnection_GroupHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名(_E): 的本地化字符串。
        /// </summary>
        public static string ServerConnection_Host {
            get {
                return ResourceManager.GetString("ServerConnection_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码(_P): 的本地化字符串。
        /// </summary>
        public static string ServerConnection_Password {
            get {
                return ResourceManager.GetString("ServerConnection_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名(_U): 的本地化字符串。
        /// </summary>
        public static string ServerConnection_UserName {
            get {
                return ResourceManager.GetString("ServerConnection_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名和密码验证 的本地化字符串。
        /// </summary>
        public static string ServerConnection_UserNamePassword {
            get {
                return ResourceManager.GetString("ServerConnection_UserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 身份验证 的本地化字符串。
        /// </summary>
        public static string ServerConnection_Windows {
            get {
                return ResourceManager.GetString("ServerConnection_Windows", resourceCulture);
            }
        }
    }
}
